# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ca574a723c34079a38839c96144a3d0c7f8f7eeac6b76d6ffb9e7f35fcd1e4bf65746e356f26334be09517f9c62ad7d4847597809ea82563043f7b3a9bae84a

test:
  secret_key_base: 4432bfd88c2952463e12e99960a163437a67b045ebe6d1f54027058c91fdc283935c3fbcfd58ff81034ccc3a57a7d08884dd16aac9f95aee8bb32d523d35bfb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
